import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [data, setData] = useState([])

  async function fetcher() {
    await fetch(
      'https://wonderful-mushroom-0f8671c10.azurestaticapps.net/api/get'
    )
      .then((res) => res.json())
      .then((res) => setData(res))
  }

  useEffect(() => {
    fetcher()
  }, [])

  if (Array.isArray(data) && !data.length) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Dog Facts</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className={styles.title}>Loading...</h1>
      </div>
    )
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Dog Facts</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Dog Facts</h1>
          <div className={styles.grid}>
            {data.map((arr, i) => (
              <a
                href="https://dukengn.github.io/Dog-facts-API/"
                className={styles.card}
                key={i}
              >
                <p>{arr.fact}</p>
              </a>
            ))}
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://azure.microsoft.com/en-us/services/app-service/static/"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <img src="/azure-1.svg" alt="Azure Logo" width={72} height={16} />
            </span>
            Azure Static Web Apps
          </a>
        </footer>
      </div>
    )
  }
}
