import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ data = ['1', '2', '3', '4'] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Dog Facts</h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {data.map((factItem, index) => {
            return (
              <a
                href="https://dukengn.github.io/Dog-facts-API/"
                className={styles.card}
                key={factItem[index]}
              >
                <h2>Dog Fact &rarr;</h2>
                <p className={styles.fact}>{factItem.fact}</p>
              </a>
            )
          })}
        </div>
      </main>
    </div>
  )
}
export async function getStaticProps(context) {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch(
    'https://wonderful-mushroom-0f8671c10.azurestaticapps.net/api/get'
  )
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: { data },
  }
}
